# Travis-CI Build for OpenRA
# see travis-ci.org for details

language: csharp
mono: 4.6.1

# http://docs.travis-ci.com/user/migrating-from-legacy
sudo: false

cache:
  directories:
  - thirdparty/download

addons:
  apt:
    packages:
    - lua5.1
    - nsis
    - nsis-common
    - dpkg
    - markdown

#env:
#  secure: "C0+Hlfa0YGErxUuWV00Tj6p45otC/D3YwYFuLpi2mj1rDFn/4dgh5WRngjvdDBVbXJ3duaZ78jPHWm1jr7vn2jqj9yETsCIK9psWd38ep/FEBM0SDr6MUD89OuXk/YyvxJAE+UXF6bXg7giey09g/CwBigjMW7ynET3wNAWPHPs="

# Fetch dependencies
# Run the build script
# Check source code with StyleCop
# call OpenRA to check for YAML errors
# Run the NUnit tests
script:
 - travis_retry make all-dependencies
 - make all SDK="-sdk:4.5"
 # - make check
 # - make check-scripts
 # - make test
 - make nunit

# Only watch yupgialert branch and release tags
branches:
 only:
   - /^yupgi-.*$/
   - /^r[0-9]+$/

before_deploy:
 - export PATH=$PATH:$HOME/usr/bin
 - echo $DOTVERSION
 - bash ${TRAVIS_BUILD_DIR}/packaging/package-opmod.sh

deploy:
  provider: releases
  api_key:
    secure: Qrg/nSLCo6L1b7B3Wn2U2eyOGY7c+BzfGS5cD9yJBkx4iQ5K8SkAqbjVzRDUeZ1jsjUwmWgQ6j5Y8siC7ACJQxfJ9s/GZ1LU7Xfz1JqhbR44xyCyVpGkcYOA8LPpgr8AcBBHbpmLwUONxp09GHWN9kdMNAzDYl+XlZk5quH7GvgcIAP0F2GCLew8JRr8OgYbXbfTnHp7B3GqEbmqZWt4YivxIHt2zarMIN2lHrg1Zopp/+GUXGBbE6DRQdR5JkvQy9m+uX7fLTtSo8bL44GYo8mkunm641pU6dV0GClcE8+Mw6CLKgFrB4M85yGyv1gCMVLQBt8lEV7VaWMLI5e9dMvd2CpsWEVHukG5euedoWH11IW4ugqP3vlBTU6ArXT56jeb5jZCMkrp4fZPLzs+/hSmuQ0j3tE+gBPZX8B4hkJS+yY9h7GEHDGengu3kHsoJ/KX2n1UGut3LOYG5P+XUUFSrhwnnj4ckbU3PAQ2capmjZsNaWyWVxm3Mn5lWg7nMyem0x+mKFrIG3wUxI9b1F3jElAN29SCqSnd4YxyMdyGM9cpFdUf/c50BhDpurfqbtVAfVjG8EaWBXLpw9vib6TyMF8WCsmHbd95s2j0QuzSKiu2QpTlFSU+kIonrfC3HCeaSnqJZ966/kalfK2B6DUn9T85LYYhMT39DFW35iQ=
  file: ${TRAVIS_BUILD_DIR}/packaging/yupgi-${TRAVIS_COMMIT}.zip
  skip_cleanup: true
  on:
    repo: forcecore/OpenRA
    branch: yupgi-*
